### ISSUE TITLE
NA Compatibility when using XGBoost

### ISSUE THREAD

**Issue by blucena** [numeristical/introspective#11]
XGBoost allows NA values (that is part of its power).  We should explicitly test NA as a particular feature value when appropriate, and also think of a way to display it in the feature_dependence_plot.  It should also be compatible to have NA in the explain_prediction_difference.

**Comment by bholligan** [comment]
Hey! Encountered this exact problem and have a recommendation.

`np.nanmax()` and `np.nanmin()` will exclude null values. This was causing issues within the model_xray() method.

The changes can be made in the following line of code:
```python
col_values = np.linspace(np.min(self.data_values[:,column_num]),
                    np.max(self.data_values[:,column_num]),resolution)
```

**Comment by blucena** [comment]
This has been resolved.  Thanks for the fix @bholligan !
