### ISSUE TITLE
Installation fails using `pip install ml_insights' on mac and Ubuntu

### ISSUE THREAD

**Issue by pramitchoudhary** [numeristical/introspective#21]
* ML Inspector version: the latest available version
* Python version: 2.7.6/2.7.9
* Operating System: Ubuntu/Mac

### Description

Was trying to install the binaries

### What I Did

*cmd:* pip install ml_insights
*Output:*
```
Collecting ml_insights
  Downloading ml_insights-0.0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-8Q_qzy/ml-insights/setup.py", line 9, in <module>
        with open('HISTORY.rst') as history_file:
    IOError: [Errno 2] No such file or directory: 'HISTORY.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-8Q_qzy/ml-insights/
```
*workaround:* _pip install -e git+https://github.com/numeristical/introspective.git#egg=ml-insights_

**Comment by blucena** [comment]
@pramitchoudhary Thanks for posting the bug!  This should be fixed now.  Please upgrade to the latest version (0.0.9) with `pip install -U ml_insights`
