### ISSUE TITLE
Confidence Interval calculation

### ISSUE THREAD

**Issue by LourencoVazPato** [numeristical/introspective#35]
Reading through the plot code, I noticed that you used the `x_pts_to_graph` as the `p` argument of the binomial distribution in 
https://github.com/numeristical/introspective/blob/2aedbb433f15d845a71e5f0e87207ec1e58494e4/ml_insights/modeling_utils.py#L642

Shouldn't the estimated probability (fraction of positives) be used instead, `y_pts_to_graph`?
I guess in this case the choice is irrelevant given that both have the same values, correct?

**Comment by blucena** [comment]
Hi Lourenco,

Thanks for your comment.  The error bars are drawn from a "hypothesis test" point of view.  That is, assuming the null hypothesis of perfect calibration, what is the range of values we would expect to see in the empirical probability.  So, assuming that the predicted probabilities (x) are well-calibrated, we ask what range of values would we expect to see for y (the observed fraction of 1s in the bin).  Under that assumption, Y should be (1/n) * Binomial(n, x), where n is the number of points in the bin. This way, one can view each bin as a hypothesis test, where a point outside the error bars represents a rejection of the null for that bin.  

There is another (minor) issue, in that we are ignoring that the probabilities of each trial vary slightly across the bin.  We treat each trial as having the same probability x, whereas in reality, they have slightly different probabilities which average out to x.  The consequence is that the error bars we plot are actually slightly wider than they would be if we simulated the "coin flips" to have the slightly different probabilities.

Does this make sense?  It's possible I'm missing something.

**Comment by LourencoVazPato** [comment]
Hi Brian.

Under your assumptions, your solution seems correct to me. Thank you for clearing this out.

Then, I guess I am working with other assumptions, hence the proposed changes. I have the same "hypothesis test" but with the assumption that each bin has probability p=fraction_of_positives. And then compute the 95% confidence interval for that hypothesis. 
You can see the resulting error bars in the following plot.


![image](https://user-images.githubusercontent.com/26346726/169101178-78d144e9-f98f-4785-85b7-b7f274329c2f.png)

**Comment by blucena** [comment]
Yes, it is reasonable to look at it from that point of view as well.  Essentially, you are creating a confidence interval around the "true probability" in the bin.

In terms of the code, I think the best idea is to have the option to do it either way.  Perhaps we add an argument called `ci_ref` (confidence interval reference) with options `axis` and `point` to choose whether you want the confidence interval around the existing way (`axis`) or your proposed way (`point`).  Does that sound reasonable?

Would you be interested in working on this? :)

**Comment by LourencoVazPato** [comment]
Yes, sure I can contribute on this :)

**Comment by blucena** [comment]
Great!  I assigned it to you. :)
