### ISSUE TITLE
Possible bug with multiclass calibration function 

### ISSUE THREAD

**Issue by yandiwu** [numeristical/introspective#39]
* ML Inspector version: 1.0.2
* Python version: 3.7.12
* Operating System: macOS

### Description

I am trying to use the SplineCalib() function for multiclass calibration, but when I try to fit my training data to a model, I get an Attribute Error. This is potentially because "SplineCalib()" has no unity_prior_weightvec argument, although it does have arguments that are similar. I recognize this may be a user error- apologies in advance if that's the case! 

### What I Did

```
calib1 = mli.SplineCalib()

X_train = df_train_all[['preds', 'attribute_1', 'attribute_2']].to_numpy() #a pandas dataframe with predictions and some attributes, and labels 
Y_train = df_train_all['labels'] 

calib1.fit(X_train, Y_train)
```

### Full Error Message: 

/opt/conda/lib/python3.7/site-packages/splinecalib/splinecalib.py:212: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.unity_prior_gridpts=='default':
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_858/2675072074.py in <module>
----> 1 calib1.fit(X_train_std_user_cohorts, Y_train_sample_user_cohort)

/opt/conda/lib/python3.7/site-packages/splinecalib/splinecalib.py in fit(self, y_model, y_true, verbose)
    192 
    193         if self.n_classes > 2:
--> 194             self._fit_multiclass(y_model, y_true, verbose=verbose)
    195         else:
    196             if len(y_model.shape) == 2:

/opt/conda/lib/python3.7/site-packages/splinecalib/splinecalib.py in _fit_multiclass(self, y_model, y_true, verbose)
    295                             unity_prior_gridpts = self.unity_prior_gridpts))
    296             self.binary_splinecalibs[i].fit(y_model[:,i],
--> 297                                             (y_true==i).astype(int))
    298 
    299     def _get_knot_vec(self, y_model):

/opt/conda/lib/python3.7/site-packages/splinecalib/splinecalib.py in fit(self, y_model, y_true, verbose)
    196             if len(y_model.shape) == 2:
    197                 y_model = y_model[:,1]
--> 198             self._fit_binary(y_model, y_true, verbose=verbose)
    199 
    200     def _fit_binary(self, y_model, y_true, verbose=False):

/opt/conda/lib/python3.7/site-packages/splinecalib/splinecalib.py in _fit_binary(self, y_model, y_true, verbose)
    218                                                         np.ones(99),
    219                                                         1/18*np.ones(18)))
--> 220             coda_wt = self.unity_prior_weight / np.sum(self.unity_prior_weightvec)
    221             weightvec = np.concatenate((np.ones(len(y_model)), 
    222                                         coda_wt * self.unity_prior_weightvec))

**AttributeError: 'SplineCalib' object has no attribute 'unity_prior_weightvec'**

**Comment by blucena** [comment]
Hi - thanks for posting this issue.  There is definitely a bug that should be addressed.  There also may be issues with how you are using the function.  

The intention when one calls
`calib1.fit(a,b)`
is that the first argument (in this case, `a`) is a set of predicted probabilities and the second argument (`b`) is the answers.  If you are trying to do binary calibration, `b` should be a vector of 0s and 1s, if you are doing calibration on `m` classes, then `b` should be a vector of integers from 0 to m-1.

In the multiclass case (which seems to be what you are doing), `a` should then be a matrix of numbers of shape (n,m) (n rows and m columns) where the rows sum to one (and n is the number of data points, same as the length of `b`).  These are the predicted, but uncalibrated, probabilities.  From your code, it looks like the first argument has 3 columns, ('preds','attribute1','attribute2') and from the names, I suspect they are not the probabilities of the different classes.  The matrix `a` should contain only numbers between 0 and 1, such that the rows sum to one, and the number of columns is the number of classes.

There is also a bug in how the code handles this, and you've exposed some other problems, so thanks for filing this!  I will work on a fix, but it won't help you unless you get your input into the right form.

Thanks!
-Brian

**Comment by blucena** [comment]
This has been fixed.  Please let me know if you want more assistance on getting it to work for your project.  Thanks for pointing out this bug!
